{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hello-fastify.serviceAccountName" . }}
  labels:
    {{- include "hello-fastify.labels" . | nindent 4 }}
{{- end -}}
